### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by luciascarlet** [jumbojett/c9.ide.theme.jett#2]
This isn't an issue, but what syntax theme are you using in the screenshot?

**Comment by jumbojett** [comment]
@bitlaneco Good question. It was the initial version of the "jett theme." (https://github.com/jumbojett/c9.ide.theme.jett/commits/master/ace.themes/jett.css)

I've been tweaking it little by little in hopes to make it easier on the eyes. Do you prefer it over the current version?

**Comment by luciascarlet** [comment]
I actually highly prefer the screenshot version over the one from the release. I feel like this old version of the Jett syntax theme was softer looking and therefore easier on the eyes than the current version and more familiar due to its use of Base16-style colouring. It highly reminds me of One Dark, which is one of my favourite syntax themes.

03.10.2016, 16:57, "Michael Jett" notifications@github.com:

**Comment by bitlaneco** [comment]
It highly me of One Dark, one of my favourite syntax themes.

03.10.2016, 16:57, "Michael Jett" <notifications@github.com>:

**Comment by jumbojett** [comment]
I appreciate the feedback! I'm always unsettled when it comes to design. :) This might be a good area to let the user choose.

**Comment by bitlaneco** [comment]
I also think it'd be nice to still offer the release theme when it comes to the actual theme. I didn't like the one from the current state of the repository much personally.

**Comment by DrianHillman** [comment]
Another question for you @jumbojett: does this only work on localhost, in SDK mode? Is there a way to add this theme to my c9.io instances?

**Comment by jumbojett** [comment]
@DrianHillman it requires core functions. It will only work on c9.io if the core cloud9 team chooses to incorporate the plugin. It wouldn't hurt to send them a message asking to do so. :)
