### ISSUE TITLE
Can't make it work on new version

### ISSUE THREAD

**Issue by BlueFRJ** [jumbojett/c9.ide.theme.jett#3]
Hi!

I'm not sure if I did something wrong, but I'm not able to make this work on C9 Version 3.1.3809 (61beb91d0f). I follow every step I can (on 2nd step instead of c9sdk/configs/client-default.js I edit configs/ide/default.js since the client-default.js does not exist) and when I initiate the server and restart nothing happens. 

Am I doing something wrong? I'd really appreciate any help, since this is the only theme I have found for C9 and I really like it.

Thanks

**Comment by jumbojett** [comment]
@BlueFRJ Thanks for the feedback. Does the option for the theme show in step 5? Can you open up chrome inspector to see if there are any errors?

**Comment by jumbojett** [comment]
Two other things... 

1. Make sure you run c9 ide in `--collab` mode.
2. If you're using the `--packed` option you'll have to `scripts/makestandalone.sh --compress` beforehand.

**Comment by BlueFRJ** [comment]
Hi. The option for the theme is not showing. The chrome inspector doesn't throw any important errors (other c9 instances also have these errors, so I guess they wont be a problem). Here are the errors and the theme option not being available:
![image](https://user-images.githubusercontent.com/15110170/30481963-6346a3e0-9a21-11e7-8ec3-0296dd2ef643.png)
Also, the terminal is on the screenshot in case I spelled something wrong. As far as I know, I'm not using the --packed option, it's a new env.

Thank you!

**Comment by jumbojett** [comment]
@BlueFRJ I just tried it out with the latest version of C9 sdk and it renders in Chrome. Try the following and see if it works:

1. Go to the C9 directory `git stash` to save your changes and reset.
2. Upload [update.patch.txt](https://github.com/jumbojett/c9.ide.theme.jett/files/1306447/update.patch.txt) to this directory.
3. `git apply update.patch.txt`
4. `node server.js -p 8080 -a : --collab`
5. Visit http://localhost:8080.  Go to the settings > Themes and choose the option next to the flat white theme.
6. Refresh your browser twice.

Let me know if this fixes it!

**Comment by BlueFRJ** [comment]
I tried using linux, and I got an almost full result!

![screenshot from 2017-09-15 16-52-46](https://user-images.githubusercontent.com/15110170/30488352-5b8d7fa6-9a36-11e7-836e-5812f53ea1ea.png)

But I think I messed up with some basic ideas, so I have some questions:

-Can I use this on web version of C9?
-if not, Is there any OS preference?
-How can I make the fonts and the color scheme work?

I'm such a newbie with this, so sorry for bothering :)

Thank you!

**Comment by jumbojett** [comment]
Looking good! 

> -Can I use this on web version of C9?

Since it uses core functions, the C9 team would need to enable the plugin in production. The short answer is, "I don't think it can be used on c9.io."

> if not, Is there any OS preference?

Nope! It renders best on Chrome though.

> How can I make the fonts and the color scheme work?

Your screenshot has the most recent look and feel. If you want to use old one pictured in the README, refer to this https://github.com/jumbojett/c9.ide.theme.jett/issues/2. You should be able to checkout an older revision to get the other look and feel.
