### ISSUE TITLE
Cannot install your template

### ISSUE THREAD

**Issue by agazzi** [jumbojett/c9.ide.theme.jett#4]
Hello,

I'm new with cloud9 IDE, you've mention to c9sdk but where is this folder in my cloud workspace cloud9 instance ? i have activated your plugin when i move to ~/.c9/plugins path but when i enable this theme, no new theme available, can you help me pls ?

**Comment by jumbojett** [comment]
@agazzi this plugin only works for the local version of cloud9.

See this line. https://github.com/c9/core/blob/master/README.md#installation

Are you trying to activate it locally?

**Comment by agazzi** [comment]
@jumbojett okay i understand, sorry for my bad, i try to install in local now, thank you.
