### ISSUE TITLE
I have no file named client-default.js in c9sdk/configs/

### ISSUE THREAD

**Issue by agazzi** [jumbojett/c9.ide.theme.jett#5]
everything is in the title

**Comment by agazzi** [comment]
okay, i have manually create this file from c9sdk github repo, but now i have see  your installation guide and i have only default flat theme, when i check i plugin explorer, i can't found c9.ide.themes.jett, any idea ?

**Comment by jumbojett** [comment]
@agazzi see this item. https://github.com/jumbojett/c9.ide.theme.jett/issues/3
The instructions are a little out-dated in my readme. I attached a patch on #3 that should take care of it for you.

**Comment by agazzi** [comment]
Thank you for everyone, it's work for me
