### ISSUE TITLE
Issue installing (even after applying patch)

### ISSUE THREAD

**Issue by nshki** [jumbojett/c9.ide.theme.jett#6]
Hi there. I was digging through some past issues (mainly #3) and was using those as reference to try and install your theme. I'm using a DigitalOcean droplet as my server and C9 version 3.1.3993.

---

## The Error:

![screenshot 2017-11-17 at 2 14 53 pm](https://user-images.githubusercontent.com/1121087/32964584-b4c06b96-cba1-11e7-9c29-9df883f86cfc.png)

---

## How I Got There:

1. Installed the C9 SDK:
```
git clone git://github.com/c9/core.git c9sdk
cd c9sdk
scripts/install-sdk.sh
```
2. Cloned the Jett Theme:
```
cd plugins
git clone git@github.com:jumbojett/c9.ide.theme.jett.git
cd ..
```
3. Upload [update.patch.txt](https://github.com/jumbojett/c9.ide.theme.jett/files/1306447/update.patch.txt) to root of sdk repo and apply:
```
git apply update.patch.txt
```
4. Run server
```
node server.js -l 0.0.0.0 -a : --collab
```
5. Visit in browser

---

Digging through the code a bit, it seems that on [this line](https://github.com/jumbojett/c9.ide.theme.jett/blob/090a693c33c870564f4302d8e9f3a5f41c2b13e6/plugin.js#L440), `rules` gets set to `null`. I'm not sure if that means stylesheets aren't getting compiled on my end. I tried running `scripts/makestandalone.sh` and running the server, but that didn't change the error.

So I'm a bit stumped, and I definitely want to use your beautiful theme. Any help would be really appreciated.

EDIT: I tried following the same process except with version 3.1.3809 (the same version used in #3) but still got the same error. Refreshed a couple times each time to make sure caches weren't affecting it.

**Comment by jumbojett** [comment]
@BlueFRJ Any insights?

**Comment by jumbojett** [comment]
@nshki sorry to hear this. Are you still unable to get it working? I appreciate the detailed steps. I can look into it later on today if you're still blocked.

**Comment by nshki** [comment]
@jumbojett Thanks for the reply. I'm still blocked, sadly!

**Comment by jumbojett** [comment]
@nshki I just went through your steps and was able to successfully launch C9 w/the jett theme. (On my Mac) What OS are you using? Make sure you're not loading any custom plugins from your home directory.

**Comment by nshki** [comment]
@jumbojett I'm using Ubuntu 17.10 on a newly created DigitalOcean droplet. I'm not loading any custom plugins either.

I'm wondering if there's some package the macOS ships with that Ubuntu 17.10 doesn't that is affecting my setup...

EDIT: Just tried this on macOS and I still get the same error.

**Comment by nshki** [comment]
@jumbojett Sorry about the double post. What version of Node are you using?

**Comment by jumbojett** [comment]
@nshki Interesting. Thanks for the details. I'll try to look into it as soon as I can.

In the meantime - This might be hack'y but an easy way to get it working. Try replacing the contents of the compiled flat-white css file with https://github.com/jumbojett/c9.ide.theme.jett/blob/master/css/compile_jett.css.

**Comment by jumbojett** [comment]
@nshki I setup a VM and still cannot reproduce the error. When you were installing c9 core did you receive any errors in your console? What version of nodejs are you using? I'm able to get this running on node `v6.4.0`

**Comment by nshki** [comment]
@jumbojett Huh, super interesting. I'm using Node 6.4.0 as well. Just tried it again and verified the Node version and still the same error.

**Comment by NickToony** [comment]
Also similar issue: Unable to apply the patch anymore. Using Ubuntu 17 (and tried 16).
